### ISSUE TITLE
Handling Updates To Existing GLEIF Records

### ISSUE THREAD

**Issue by radix0000** [openownership/bodspipelines#9] opened 2023-03-31 17:02 UTC
Currently while new GLEIF records will result in new BODS statements being created, if existing records are modified there is no mechanism for propagating those changes (e.g. an address change on a LEI record will not result in an updated BODS statement). While there are certainly approaches that could address this, they need work in the context of a pipeline (sequential processing). Given that this is current targeting BODS v0.2 this also means navigating change over time issues (https://github.com/openownership/data-standard/issues/392). While producing an updated statement is certainly possible, the previous statement can be linked to other statements and if those links need to be updated as well, the problem becomes much more complex.

**Comment by kd-ods** [comment] 2023-05-18 15:28
> While producing an updated statement is certainly possible, the previous statement can be linked to other statements and if those links need to be updated as well, the problem becomes much more complex.

This is a succinct statement of the implementation problems caused by the `replacesStatements` way of handling change over time. Hopefully the [changes proposed for the v0.4 BODS release](https://github.com/openownership/data-standard/discussions/475) will make such handling easier.

I think we do need to deal with this issue with the current rendering of GLEIF data in BODS 0.2, though. I think there are prob 3 options:

1) Leave as is. But we have to warn users that the data is a mixture of old and new information.

2) Regenerate the data anew each time the pipeline is run. Generate new statementIDs for all statements (perhaps ensure that they are a function of the date the pipeline is run?). So we can explain to users that the dataset is a snapshot of the data at a point in time. If people want to use snapshots from different points in time to see what's changed, they'll need to rely on the LEIs themselves to link statements about the same entity.

3) Do a proper `replacesStatements` implementation which - as @radix0000 says - is complex.

My preference is (2) if it's not technically difficult. 

If that's how we resolve this, then we could even do a blog post explaining what we've done, why, and how it would be a different matter if we adopt the proposal linked to above.

**Comment by StephenAbbott** [comment] 2023-05-18 15:38
@kd-ods Agree that option 2 is preferable and I would love to get an estimate from @radix0000 for how much of his time that work would take so that we could prioritise this.

Would be good to wrap this into a piece of work explaining how we handle change over time here and with other datasets so that we can again mention our ongoing BODS v0.4 work on this topic.

**Comment by kd-ods** [comment] 2023-06-16 16:45
@StephenAbbott - Ed and I have been considering whether option 3 is actually preferable. It's something to discuss next week.

In the meantime, it's worth noting the following info regarding how the golden and delta files handle the lifecycle of LEI records:

> In addition to Golden Copy Files, which always contain the most recent version of **all** LEI records, GLEIF makes Delta Files available.

> Relationship records with any status other than “PUBLISHED” or “LAPSED” are removed from the Golden Copy.
> 
> Delta Files that reflect this change contain the record to be deleted with an added deletion flag in the Extension field.

From [GLEIF Golden Copy and Delta Files Specification and User Manual](https://www.gleif.org/lei-data/gleif-golden-copy/2022-02-23_gleif-golden-copy-and-delta-files_v2.2-final.pdf)

There is also a useful Lifecycle diagram on page 27 of [State Transition and Validation Rules for Common Data File formats](https://www.gleif.org/media/pages/about-lei/common-data-file-format/current-versions/level-2-data-reporting-exceptions-2-1-format/7bff93b2fa-1686922996/2023-03-07_state-transition-validation-rules_v2.7.1_final.pdf).

**Comment by kathryn-ods** [comment] 2024-08-21 14:29
Closing this issue as my understanding is this has been implemented now using the delta files

**Closed as completed by kathryn-ods** 2024-08-21 14:29 UTC
